# Generated by Django 5.2.3 on 2025-07-02 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Providers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=100)),
                ("phone_number1", models.CharField(max_length=20)),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "providers",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="ProductProviders",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "product_id",
                        "provider_id",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="products.products",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="providers.providers",
                    ),
                ),
            ],
            options={
                "db_table": "product_providers",
                "managed": True,
            },
        ),
    ]
